################################################################################
# Copyright 2016 spriteCloud B.V. All rights reserved.
# Generated by LapisLazuli, version 0.8.3
# Author: "barzilay" <barzilay@spritecloud.com>

Given(/^I navigate to the (.*) in (.*)$/) do |site,language|
  config_name = "#{site.downcase}.#{language.downcase}.home"
  #Set language for all other steps
  @language = language
  if has_env?(config_name)
    url = env(config_name)
    browser.goto url
  else
    error(:env => config_name)
  end
end