################################################################################
# Copyright 2016 spriteCloud B.V. All rights reserved.
# Generated by LapisLazuli, version 0.8.3
# Author: "barzilay" <barzilay@spritecloud.com>

Given(/^I am on a product lister page$/) do
  config_name = "site.#{@language.downcase}.plp_page"
  if has_env?(config_name)
    url = env(config_name)
    browser.goto url
  else
    error(:env => config_name)
  end
end

When(/^I select one of the items$/) do
  item = browser.a(:href => /\/itm\//)
  item.click
end

Then(/^I am on the Product detail page of the selected item$/) do
  browser.url.include? "/itm/"
end

Then(/^I can see details of the product$/) do
  item = browser.wait(
    :timeout => 30,
    :selectors => [{
                     :tag_name => 'div',
                     :class => "itemAttr"
                   }]
  )
  raise("Cannot find details section on page") unless item && item.visible?

  browser.take_screenshot
end